package com.hp.schemas.sm._7;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2021-09-13T16:19:05.802+03:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "ContactCenter",
                  wsdlLocation = "file:/C:/Back-up/WorkspaceBackup/TeamsiteWorkspace2020/contact-service/src/main/resources/wsdl/ContactCenter.wsdl",
                  targetNamespace = "http://schemas.hp.com/SM/7")
public class ContactCenter_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.hp.com/SM/7", "ContactCenter");
    public final static QName ContactCenter = new QName("http://schemas.hp.com/SM/7", "ContactCenter");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Back-up/WorkspaceBackup/TeamsiteWorkspace2020/contact-service/src/main/resources/wsdl/ContactCenter.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ContactCenter_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Back-up/WorkspaceBackup/TeamsiteWorkspace2020/contact-service/src/main/resources/wsdl/ContactCenter.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContactCenter_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContactCenter_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactCenter_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ContactCenter_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ContactCenter_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ContactCenter_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ContactCenter
     */
    @WebEndpoint(name = "ContactCenter")
    public ContactCenter getContactCenter() {
        return super.getPort(ContactCenter, ContactCenter.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactCenter
     */
    @WebEndpoint(name = "ContactCenter")
    public ContactCenter getContactCenter(WebServiceFeature... features) {
        return super.getPort(ContactCenter, ContactCenter.class, features);
    }

}
