package com.hp.schemas.sm._7;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2021-09-13T16:19:05.406+03:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://schemas.hp.com/SM/7", name = "ContactCenter")
@XmlSeeAlso({ObjectFactory.class, xmlmime.ObjectFactory.class, com.hp.schemas.sm._7.common.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ContactCenter {

    @WebMethod(operationName = "RetrieveContactCenter", action = "Retrieve")
    @WebResult(name = "RetrieveContactCenterResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveContactCenterResponse")
    public RetrieveContactCenterResponse retrieveContactCenter(

        @WebParam(partName = "RetrieveContactCenterRequest", name = "RetrieveContactCenterRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        RetrieveContactCenterRequest retrieveContactCenterRequest
    );

    @WebMethod(operationName = "RetrieveContactCenterKeysList", action = "RetrieveKeysList")
    @WebResult(name = "RetrieveContactCenterKeysListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveContactCenterKeysListResponse")
    public RetrieveContactCenterKeysListResponse retrieveContactCenterKeysList(

        @WebParam(partName = "RetrieveContactCenterKeysListRequest", name = "RetrieveContactCenterKeysListRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        RetrieveContactCenterKeysListRequest retrieveContactCenterKeysListRequest
    );

    @WebMethod(operationName = "RetrieveContactCenterList", action = "RetrieveList")
    @WebResult(name = "RetrieveContactCenterListResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "RetrieveContactCenterListResponse")
    public RetrieveContactCenterListResponse retrieveContactCenterList(

        @WebParam(partName = "RetrieveContactCenterListRequest", name = "RetrieveContactCenterListRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        RetrieveContactCenterListRequest retrieveContactCenterListRequest
    );

    @WebMethod(operationName = "UpdateContactCenter", action = "Update")
    @WebResult(name = "UpdateContactCenterResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "UpdateContactCenterResponse")
    public UpdateContactCenterResponse updateContactCenter(

        @WebParam(partName = "UpdateContactCenterRequest", name = "UpdateContactCenterRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        UpdateContactCenterRequest updateContactCenterRequest
    );

    @WebMethod(operationName = "CreateContactCenter", action = "Create")
    @WebResult(name = "CreateContactCenterResponse", targetNamespace = "http://schemas.hp.com/SM/7", partName = "CreateContactCenterResponse")
    public CreateContactCenterResponse createContactCenter(

        @WebParam(partName = "CreateContactCenterRequest", name = "CreateContactCenterRequest", targetNamespace = "http://schemas.hp.com/SM/7")
        CreateContactCenterRequest createContactCenterRequest
    );
}
